url: "htpp://Bobbinson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Emanuel Papiez" # the name of your site
bio: Undergraduate Software Developer

email:
  address: "emanuelp@windowslive.com"
  text: "emanuelp@windowslive.com"



# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: Bobbinson
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
#medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
